# -*- coding: utf-8 -*-
"""dsq2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhyqjQuxsNBPz3XwYT1Ox83SN_aP5YvV
"""

def list_to_matrix(lst):
    matrix = []

    while len(lst) < 9:
        lst.append(None)

    for i in range(0, 9, 3):
        matrix.append(lst[i:i+3])

    return matrix


def tuple_statistics(lst):
    data_tuple = tuple(lst)

    total = 0
    count = 0

    for i in lst:
        total += i
        count += 1

    mean_value = total / count

    sorted_list = sorted(lst)

    n = len(sorted_list)

    if n % 2 == 0:
        median_value = (sorted_list[n//2 - 1] + sorted_list[n//2]) / 2
    else:
        median_value = sorted_list[n//2]

    mode_value = None
    max_count = 0

    for i in sorted_list:
        freq = sorted_list.count(i)

        if freq > max_count:
            max_count = freq
            mode_value = i

    return {
        "tuple": data_tuple,
        "mean": mean_value,
        "median": median_value,
        "mode": mode_value
    }


def final_result(lst):
    matrix_result = list_to_matrix(lst.copy())

    stats_result = tuple_statistics(lst)

    result = {
        "Matrix_Function": matrix_result,
        "Tuple_Statistics_Function": stats_result
    }

    return result


user_list = list(map(int, input("Enter numbers separated by space: ").split()))

output = final_result(user_list)

print(output)